# Generated by Django 4.0.3 on 2022-03-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailout',
            name='filter_value',
            field=models.CharField(default='123', max_length=100, verbose_name='filter value'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailout',
            name='filter_field',
            field=models.CharField(choices=[('TAG', 'user tag'), ('PREFIX', 'phone prefix')], max_length=6, verbose_name='filter type'),
        ),
    ]
