# Generated by Django 4.0.3 on 2022-03-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationsapp', '0002_mailout_filter_value_alter_mailout_filter_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailout',
            name='filter_field',
            field=models.CharField(choices=[('tag', 'user tag'), ('cell_provider_prefix', 'phone prefix')], max_length=20, verbose_name='filter type'),
        ),
    ]
