# Generated by Django 4.0.3 on 2022-03-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationsapp', '0003_alter_mailout_filter_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailoutmessage',
            name='sent_at',
            field=models.DateTimeField(blank=True, verbose_name='sent at'),
        ),
        migrations.AlterField(
            model_name='mailoutmessage',
            name='status',
            field=models.CharField(max_length=100, verbose_name='message status'),
        ),
    ]
