# Generated by Django 4.0.3 on 2022-03-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationsapp', '0004_alter_mailoutmessage_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailoutmessage',
            name='status',
            field=models.CharField(blank=True, max_length=100, verbose_name='message status'),
        ),
    ]
