# Generated by Django 4.0.3 on 2022-03-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationsapp', '0005_alter_mailoutmessage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailoutmessage',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='sent at'),
        ),
    ]
