# Generated by Django 4.0.3 on 2022-03-24 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0011_taskresult_periodic_task_name'),
        ('notificationsapp', '0006_alter_mailoutmessage_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailoutmessage',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_results.taskresult'),
        ),
    ]
