# Generated by Django 4.0.3 on 2022-03-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationsapp', '0007_mailoutmessage_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailoutmessage',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='task ID'),
        ),
    ]
